import { StyleSheet } from "react-native";
export const StylesMaps = StyleSheet.create({
    ContainerMaps:{
        flex: 1,
        backgroundColor: '#111',
        alignItems: 'center',
    },
    ContainerMain: {
        width: '100%',
        height: '100%',
    },
    ContainerHeader: {
        borderBottomColor: '#aaa',
        borderWidth: 1,
        height: '8%',
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 5,
        position: 'absolute',
        zIndex: 1,
        backgroundColor: '#111'
    },
    textHeader: {
        fontSize: 20,
        color: '#eee',
        letterSpacing: 2,
        fontWeight: '500',
    },
    ButtonHeader: {
        width: '50%',
        height: '80%',
        borderRadius: 10,
        borderColor: '#ddaa',
        borderWidth: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    Imagen: {
        width: 40,
        height: 40,
        resizeMode: 'contain',
    },
    Map: {
        width: '100%',
        height: '93%',
        borderColor: '#fff',
        borderWidth: 1,
        position: 'absolute',
        zIndex: 0,
    },
    ContainerButtom: {
        position: 'absolute',
        left: '0',
        bottom: '5%',
        zIndex: 1,
        borderTopColor: '#aaa',
        borderTopWidth: 1,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        height: '15%',
        alignContent: 'center',
        backgroundColor: '#111',
    },
    Button: {
        position: 'relative',
        top: '5%',
        borderRadius: 10,
        borderColor: '#ddaa',
        borderWidth: 1,
        width: '45%',
        height: '40%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#222',
    },
    TextButton:{
        fontSize: 13,
        color: '#eee',
        letterSpacing: 2,
        textAlign: 'center',
        fontWeight: '500',
    },
    ModalContainer: {
        position: 'absolute',
        left: '5%',
        top: '20%',
        width: '90%',
        height: '55%',
        padding: 20,
        alignItems: 'center',
        backgroundColor: '#222',
        borderColor: '#ddaa',
        borderWidth: 2,
        borderRadius: 20,
        gap: 25,
        
    },
    ModalTextContainer: {
        borderBottomColor: '#eee',
        borderBottomWidth: 1,
        paddingVertical: 10,
        height: '18%'
    },
    ModalTitle: {
        fontSize: 24,
        color: '#eee',
        letterSpacing: 2,
        fontWeight: '500',
    },
    ModalText: {
        fontSize: 16,
        color: '#eee',
        letterSpacing: 2,
        fontWeight: '500',
    },
    ModalButton: {
        borderColor: '#ddaa',
        borderWidth: 1,
        width: '70%',
        height: '10%',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#111'
    },
    ModalButtonText: {
        fontSize: 16,
        color: '#eee',
        letterSpacing: 2,
        fontWeight: '500',
    },
})
